# Generated by Django 5.2.7 on 2025-11-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='regNo',
            field=models.CharField(max_length=100),
        ),
    ]
